# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.


title: The Zöllei Lab
#description: The Zöllei Lab


email: lzollei-at-mgh.harvard.edu
description: >- # this means to ignore newlines until "baseurl:"
  The Zöllei Lab
logo: "/assets/logo.jpg"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: LZollei
github_username:  lillazollei

# Build settings
theme: minima
#theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
#  - jekyll-remote-theme
#remote_theme: pages-themes/minimal@v0.2.0


site:
  logo: https://scholar.harvard.edu/sites/scholar.harvard.edu/files/lillazollei/files/lillazollei.cr_.sm2_.jpg

header_pages:
  - index.markdown
  - people.markdown
  - about.markdown
  - projects.markdown
  - jobs.markdown
  - publications.markdown
  - software.markdown


minima:
  social_links:
    - { platform: github,  user_url: "https://github.com/lillazollei" }
    - { platform: github,  user_url: "https://github.com/freesurfer/freesurfer" }
    - { platform: twitter, user_url: "https://twitter.com/LZollei" }
    - { platform: mastodon, user_url: "https://mastodon.online/@lzollei" }
    
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
